# Generated by Django 5.1.5 on 2025-01-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="image",
            field=models.ImageField(upload_to="images"),
        ),
    ]
