# Generated by Django 5.1.5 on 2025-01-25 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_app_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="appCategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.category",
            ),
        ),
    ]
