# Generated by Django 5.1.5 on 2025-01-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_app_appcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='screen_shot',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
