# Generated by Django 5.1.5 on 2025-01-26 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_task_screen_shot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='screen_shot',
            new_name='image',
        ),
    ]
