# Generated by Django 5.1.5 on 2025-01-26 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_screen_shot_task_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='image',
            new_name='screen_shot',
        ),
    ]
